[package]
name    = "asteroids"
version = "0.1.0"
authors = ["Leonhard Weber <leonhard.weber@voipir.cl>", "Clemente Alarcon <clementealarcon@dsvillarrica.cl>"]

[dependencies]
sfml = {version = "*", path = "lib/sfml"}
